[package]
name = "qpick-bin"
version = "0.1.0"
authors = ["dcvetinovic@gmail.com"]
description = """
A command line tool for using with qpick library.
"""

[[bin]]
name = "qpick"

[dependencies]
serde = "*"
serde_json = "*"
fst = "*"
docopt = "0.6"
qpick = { path = "..", version = "0.1.0" }
rustc-serialize = "0.3"

[profile.release]
debug = true
opt-level = 3
